#!/usr/bin/env bash

# Colors taken from tokyonight theme
magenta2="0xffff007c"
blue="0xff7aa2f7"

options=(
	active_color="$magenta2"
	inactive_color="$blue"
	hidpi=on
	style=round
	width=4.0
)

borders "${options[@]}"
