#!/usr/bin/env bash

# Colors taken from tokyonight theme
magenta="0xffbb9af7"
magenta2="0xffff007c"

options=(
	active_color="$magenta2"
	inactive_color="$blue"
	hidpi=on
	style=round
	width=4.0
)

borders "${options[@]}"
