#!/usr/bin/env bash

# AppleAccentColor is an int, mapped to some color values.
# Approximate the colors these ints represent with following hex values:
GRAPHITE="0xff757575"
RED="0xffff5258"
ORANGE="0xfff8821c"
YELLOW="0xfffec700"
GREEN="0xff62ba46"
BLUE="0xff007aff"
PURPLE="0xffa550a7"
PINK="0xfff84f9f"
MULTICOLOR="$BLUE"

# Use the color selected in the Appearance settings as the active color
case $(defaults read -g AppleAccentColor) in
	-1)
		MACOS_ACCENT_COLOR="$GRAPHITE"
		;;
	0)
		MACOS_ACCENT_COLOR="$RED"
		;;
	1)
		MACOS_ACCENT_COLOR="$ORANGE"
		;;
	2)
		MACOS_ACCENT_COLOR="$YELLOW"
		;;
	3)
		MACOS_ACCENT_COLOR="$GREEN"
		;;
	4)
		MACOS_ACCENT_COLOR="$BLUE"
		;;
	5)
		MACOS_ACCENT_COLOR="$PURPLE"
		;;
	6)
		MACOS_ACCENT_COLOR="$PINK"
		;;
	*)
		MACOS_ACCENT_COLOR="$MULTICOLOR"
		;;
esac

ACTIVE_COLOR="$MACOS_ACCENT_COLOR"
INACTIVE_COLOR="$GRAPHITE"
HIDPI=on
STYLE=round
WIDTH=4.0
