#!/usr/bin/env bash

# Tokyonight Night Color Palette (slightly modified)
black="0xff24283b"
blue="0xff7aa2f7"
blue1="0xff1a1b26"
blue1_semitransparent="0xaa1a1b26"
cyan="0xff7dcfff"
green="0xff9ece6a"
magenta="0xffbb9af7"
orange="0xffff9e64"
purple="0xff9d7cd8"
red="0xfff7768e"
transparent="0x00000000"
white="0xffa9b1d6"
yellow="0xffe0af68"

# Defaults
BAR_BLUR_RADIUS=30
BAR_COLOR="$transparent"
BAR_CORNER_RADIUS=12
BAR_HEIGHT=24
BAR_MARGIN=6
BAR_PADDING=0
BAR_POSITION="top"
BAR_Y_OFFSET=6

BACKGROUND_BORDER_COLOR="$red"
BACKGROUND_BORDER_WIDTH=2
BACKGROUND_COLOR="$blue1_semitransparent"
BACKGROUND_CORNER_RADIUS=4
BACKGROUND_HEIGHT=24

BRACKET_BACKGROUND_BORDER_COLOR="$blue"
BRACKET_BACKGROUND_BORDER_WIDTH=0
BRACKET_BACKGROUND_COLOR="$blue1_semitransparent"
BRACKET_BACKGROUND_CORNER_RADIUS=12

ICON_BASE_FONT="SF Pro"
ICON_FONT="$ICON_BASE_FONT:Bold:14.0"

LABEL_ALIGN="center"
LABEL_BASE_FONT="DepartureMono Nerd Font"
LABEL_COLOR="$blue"
LABEL_FONT="$LABEL_BASE_FONT:Regular:16.0"
LABEL_HIGHLIGHT_COLOR="$red"
LABEL_HIGHLIGHT_FONT="$LABEL_BASE_FONT:Regular:16.0"
LABEL_PADDING=6
LABEL_Y_OFFSET=1
