# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$shlvl\
$directory\
$character"""

# Increase truncation length and add truncation symbol
[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'

[kubernetes]
disabled = true
