#!/bin/zsh
# ------------------------------------------------------------------------------
# Alias definitions for zsh.
# ------------------------------------------------------------------------------
# Marco Peluso
# marcopeluso.com
# marco AT pelu DOT so
# ------------------------------------------------------------------------------
# This file isn't automatically executed.
# Source it via .zshrc or another zsh startup file.
# ------------------------------------------------------------------------------


# zsh - {{{

# source .zshrc
alias szshrc='source ~/.zshrc'

# zsh - }}}


# ls - {{{

# list files and directories in long mode
alias l='ls -lhF'

# list files and directories in long mode (including hidden ones)
alias la='ls -lahF'

# list only hidden files and directories in long mode
alias lh='ls -lhdF .*'

# list only directories in long mode
alias ld='ls -lhdF *(/)'

# list only hidden files
alias lhf='ls -alhdF .*(.)'

# list only directories
alias lsd='ls -hFd *(/)'

# list only directories in long mode (including hidden ones)
alias lad='ls -alhFd *(/) .*(/)'

# list only hidden directories
alias lhd='ls -alhdF .*(/)'

# ls - }}}


# cd - {{{

alias cdn='cd ~/nextcloud'
alias cddf='cd ~/nextcloud/dotfiles'
alias cdfra='cd ~/nextcloud/fra-uas'

# cd - }}}


# macOS Specific - {{{

# flush dns cache (macOS)
alias flushdns-macos='sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder'

# macOS Specific - }}}

