#!/bin/zsh
# ------------------------------------------------------------------------------
# Function definitions for zsh.
# ------------------------------------------------------------------------------
# Marco Peluso
# marcopeluso.com
# marco AT pelu DOT so
# ------------------------------------------------------------------------------
# This file isn't automatically executed.
# Source it via .zshrc or another zsh startup file.
# ------------------------------------------------------------------------------


# General Stuff - {{{

# Make directory and directly cd into it. Supports directory hierarchies and
# spaces in directory names.
function mkcd() {
  mkdir -p "$*"
  cd "$*"
}

# 'ff x' finds a file named x from the current directory downwards and prints
# it's path. Works with wildcards.
function ff() {
  find . -name "$1" -print
}

# General Stuff - }}}


# VirtualBox / VMWare Fusion - {{{

# List all running VirtualBox and VMWare Fusion virtual machines
function vmlist-running() {
  echo "\n### Running VirtualBox virtual machines:\n"
  VBoxManage list runningvms

  echo "\n### Running VMWare Fusion virtual machines:\n"
  vmrun list
}


# wan.vm.vu
function vmstart-wan.vm.vu() {
  VBoxManage startvm wan.vm.vu --type headless
}
function vmshutdown-wan.vm.vu() {
  ssh -t wan@wan.vm.vu 'sudo shutdown -h now'
}

# VirtualBox - }}}
