# zsh configuration file.
# ------------------------------------------------------------------------------
# Marco Peluso
# marcopeluso.com
# marco AT pelu DOT so
# ------------------------------------------------------------------------------


# Info: zsh Startup Files - {{{
# ------------------------------------------------------------------------------

# $HOME/.zshrc: run by zsh for non-login shells

# Startup files run order (first to last):
# /etc/zshenv     - for every zsh
# $HOME/.zshenv   - for every zsh
# /etc/zprofile   - for login shells
# $HOME/.zprofile - for login shells
# /etc/zshrc      - for interactive shells
# $HOME/.zshrc    - for interactive shells
# /etc/zlogin     - for login shells
# $HOME/.zlogin   - for login shells

# Files that are run before zsh is closed (first to last):
# /etc/zlogout
# $HOME/.zlogout

# Info: zsh Startup Files - }}}


# configure script - {{{

zsh_temp_path="$HOME/.df-tmp/zsh"

# configure script - }}}


# Load aliases and functions - {{{

# if aliases file exists, load it
if [[ -f $HOME/.zshaliases ]]; then
  source $HOME/.zshaliases
fi


# if functions file exists, load it
if [[ -f $HOME/.zshfunctions ]]; then
  source $HOME/.zshfunctions
fi

# Load aliases and functions - }}}


# General Options - {{{

# Just type "/my/path" instead of "cd /my/path" to change directories
setopt AUTO_CD

# Make cd push the old directory onto the directory stack.
setopt AUTO_PUSHD

# Do not print the directory stack after pushd or popd.
setopt PUSHD_SILENT

# Have pushd with no arguments act like 'pushd $HOME'.
setopt PUSHD_TO_HOME

# Try to correct the spelling of commands.
#setopt CORRECT

# Try to correct the spelling of all arguments in a line.
#setopt CORRECT_ALL

# List jobs in the long format by default.
setopt LONG_LIST_JOBS

# Disable flow control and hence restore the ability to use C-s and C-q
setopt NO_FLOW_CONTROL

# General Options - }}}


# Set Up line Editor For Vi Mode - {{{

# enable vi mode
bindkey -v

# bind Meta-. to insert last word of previous command and stay in insert mode
bindkey -M viins "\e." insert-last-word

# bind C-R to search backwards in all modes
bindkey '^R' history-incremental-search-backward

# bind C-S to search forward in all modes
bindkey '^S' history-incremental-search-forward

# history expansion on space (do "!-3<space>" to expand and be able to edit that
# line)
bindkey ' '  magic-space

# bind history navigation to C-P and C-N in all modes
bindkey '^P' up-line-or-history

# bind history navigation to C-P and C-N in all modes
bindkey '^N' down-line-or-history

# bind C-D to forward delete next char
bindkey '^D' delete-char

# Additionaly set up basic Emacs-style navigation
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^F' forward-char
bindkey '^B' backward-char

# Set Up line Editor For Vi Mode - }}}


# Set Up Prompt - {{{

# TODO: clean this section up / redo it completely

# TODO: only enable coloring, if it's available terminal-wise

# %(x.true-string.false-string) is a conditional expression, where "x" is some arbitrary testing condition.
# "0" is true, everything else is false.
#
# If "x" is true, true-string is used, otherwise false-string is used. These strings can be empty.
#
# Special characters that can be used for "x":
# ! - Current uid. You can test, if you're root with this, since root's uid is 0.
# ? - Last exit code. Programs quit with exit code 0, if everything went right or other appropriate exit codes to indicate errors.
#
# special characters used in prompts:
# %! - event (history) number
# %? - exitcode of last command
# %n - username
# %m - hostname up to the first dot
# %M - full hostname
# %d - current working directory ($PWD)
# %/ - same as %d
# %~ - current working directory, where $HOME is shortened to "~"
# %? - last exit code
#
# %h - history number
# %# - % if unprivileged, # if privileged
#
# CHECK FOLLOWING LINKS:
# http://www.acm.uiuc.edu/workshops/zsh/prompt/escapes.html
# http://aperiodic.net/phil/prompt/
# http://kriener.org/articles/2009/06/04/zsh-prompt-magic

setopt prompt_subst

# Load colors
autoload -U colors && colors

# Set up basic color variables that are easier to use in prompt later on
PC_RES="%{$reset_color%}"
PC_GREEN="%{$fg[green]%}"
PC_RED="%{$fg[red]%}"
PC_FG1="$PC_GREEN"
PC_FG2="$PC_RED"

# Set up a variable color. It uses PC_FG1 when root, otherwise PC_FG2
PC_RDP="%(!.$PC_FG2.$PC_FG1)"

PROMPT="$PC_RDP%#$PC_RES ";
RPROMPT="$PC_RDP($PC_RES%n$PC_RDP@$PC_RES%m$PC_RDP:$PC_RES%~$PC_RDP%)$PC_RES"

# Set Up Prompt - }}}


# Set Up Completion - {{{

# TODO: clean this section up / redo it completely

autoload -U zutil

# autoload -U compinit

# load compinit even if compaudit finds insecure files TODO: is this right?
autoload -U compinit -u

autoload -U complist

# Alternate location for compinit's dumpfile. The path apparently has to exist, so you have to create it yourself.
compinit -d $zsh_temp_path/zcompdump

# See also man 1 zshcompctl zshcompsys zshcompwid.
# zshcompctl is the old style of zsh programmable completion, zshcompsys is the new completion system,
# zshcompwid are the zsh completion widgets.
# Some functions, like _apt and _dpkg, are very slow. You can use a cache in order to proxy the list of results (like the list of available debian packages) Use a cache:
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path zsh_temp_path/cache

# # matches case insensitive for lowercase
# zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

## case-insensitive (all), partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Set Up Completion - }}}


# Set Up History Saving - {{{

# Enable globally shared history (same history in every shell)
setopt SHARE_HISTORY

# When writing out the history file, older commands that duplicate newer ones
# are omitted.
setopt HIST_SAVE_NO_DUPS

# Prevent entries preceded with at least one space from being recorded into a
# history.
setopt HIST_IGNORE_SPACE

# Whenever the user enters a line with history expansion, don't execute the line
# directly. Instead, perform history expansion and reload the line into the
# editing buffer.
setopt HIST_VERIFY

# File which holds the command history
HISTFILE="$zsh_temp_path/history"

# Number of lines of history that will be saved
SAVEHIST=25000

# If $SAVEHIST and $HISTFILE are set, zsh will read $HISTSIZE lines from
# $HISTFILE at the start of an interactive session, and save the last $SAVEHIST
# lines you executed at the end of the session.
HISTSIZE=25000

# Set Up History Saving - }}}

