#!/usr/bin/env bash

# TODO: Use GNU sed instead of macOS sed, as it is a little less clunky in many cases.

# Use empty file to remember toggle state
TOGGLE="$XDG_STATE_HOME/.recording_toggle"
if [ ! -e "$TOGGLE" ]; then
  touch "$TOGGLE"
else
  rm "$TOGGLE"
fi

# WezTerm
## Don't use DepartureMono for recording.
## Use big font while recording.
## Also don't start/attach to tmux by default.
DEFAULT_TERMINAL_FONT_SIZE=18
RECORDING_TERMINAL_FONT_SIZE=44
WEZTERM_CONFIG="$XDG_CONFIG_HOME/wezterm/wezterm.lua"
if [ ! -e "$TOGGLE" ]; then
  sed -i '' 's/"DepartureMono/--"DepartureMono/' "$WEZTERM_CONFIG"
  sed -i '' "s/font_size = $DEFAULT_TERMINAL_FONT_SIZE/font_size = $RECORDING_TERMINAL_FONT_SIZE/g" "$WEZTERM_CONFIG"
  sed -i '' 's/config.default_prog/--config.default_prog/' "$WEZTERM_CONFIG"
else
  sed -i '' 's/--"DepartureMono/"DepartureMono/' "$WEZTERM_CONFIG"
  sed -i '' "s/font_size = $RECORDING_TERMINAL_FONT_SIZE/font_size = $DEFAULT_TERMINAL_FONT_SIZE/g" "$WEZTERM_CONFIG"
  sed -i '' 's/--config.default_prog/config.default_prog/' "$WEZTERM_CONFIG"
fi

# tmux
## Don't show current window and pane numbers while recording
TMUX_CONFIG="$XDG_CONFIG_HOME/tmux/tmux.conf"
if [ ! -e "$TOGGLE" ]; then
  sed -i '' 's/set -g status-right "#\[fg=#{@purple}\]#S:#I.#P"/set -g status-right "#[fg=#{@purple}]#S"/g' "$TMUX_CONFIG"
  tmux source-file "$TMUX_CONFIG"
else
  sed -i '' 's/set -g status-right "#\[fg=#{@purple}\]#S"/set -g status-right "#[fg=#{@purple}]#S:#I.#P"/g' "$TMUX_CONFIG"
  tmux source-file "$TMUX_CONFIG"
fi

# Sketchybar
## Don't show clock while recording
## Change font to JetBrains Mono while recording
SKETCHYBAR_CONFIG="$XDG_CONFIG_HOME/sketchybar/sketchybarrc"
SKETCHYBAR_THEME_TOKYONIGHT="$XDG_CONFIG_HOME/sketchybar/themes/tokyonight"
if [ ! -e "$TOGGLE" ]; then
  sed -i '' 's|source "$ITEM_DIR/clock"|#source "$ITEM_DIR/clock"|g' "$SKETCHYBAR_CONFIG"
  sed -i '' 's/LABEL_BASE_FONT="DepartureMono Nerd Font"/LABEL_BASE_FONT="JetBrainsMono Nerd Font"/g' "$SKETCHYBAR_THEME_TOKYONIGHT"
else
  sed -i '' 's|#source "$ITEM_DIR/clock"|source "$ITEM_DIR/clock"|g' "$SKETCHYBAR_CONFIG"
  sed -i '' 's/LABEL_BASE_FONT="JetBrainsMono Nerd Font"/LABEL_BASE_FONT="DepartureMono Nerd Font"/g' "$SKETCHYBAR_THEME_TOKYONIGHT"
fi

# nvim
## Disable certain plugins while recording
NVIM_INIT_LUA="$XDG_CONFIG_HOME/nvim/init.lua"
if [ ! -e "$TOGGLE" ]; then
  sed -i '' "s/require('plugins.which-key')/--require('plugins.which-key')/g" "$NVIM_INIT_LUA"
else
  sed -i '' "s/--require('plugins.which-key')/require('plugins.which-key')/g" "$NVIM_INIT_LUA"
fi

# zsh
## Disable autosuggestions while recording
ZSH_CONFIG="$XDG_CONFIG_HOME/zsh/.zshrc"
if [ ! -e "$TOGGLE" ]; then
  sed -i '' '/zsh-users\/zsh-autosuggestions/d' "$ZSH_CONFIG"
else
  sed -i '' '/zsh-users\/zsh-syntax-highlighting/a\
  zsh-users/zsh-autosuggestions
' "$ZSH_CONFIG"
fi

# TODO: fix this
# starship
## Use completely different configs depending on if recording or not
# if [ ! -e "$TOGGLE" ]; then
#   stow -D -d ~/.dotfiles -t "$XDG_CONFIG_HOME" starship
#   stow -d ~/playground/dotfiles/xdg_config_home -t "$XDG_CONFIG_HOME" starship-youtube
# else
#   stow -D -d ~/playground/dotfiles/xdg_config_home -t "$XDG_CONFIG_HOME" starship-youtube
#   stow -d ~/.dotfiles -t "$XDG_CONFIG_HOME" starship
# fi
