#!/usr/bin/env bash

# TODO: Use GNU sed instead of macOS sed, as it is a little less clunky in many cases.

# Use empty file to remember toggle state
TOGGLE="$XDG_STATE_HOME/.recording_toggle"
if [ ! -e "$TOGGLE" ]; then
  touch "$TOGGLE"
else
  rm "$TOGGLE"
fi

# Terminals
## Use big font while recording. Also don't start with tmux by default.
DEFAULT_FONT_SIZE=18
RECORDING_FONT_SIZE=36

### WezTerm
WEZTERM_CONFIG="$XDG_CONFIG_HOME/wezterm/wezterm.lua"
if [ ! -e "$TOGGLE" ]; then
  sed -i '' "s/font_size = $DEFAULT_FONT_SIZE/font_size = $RECORDING_FONT_SIZE/g" "$WEZTERM_CONFIG"
else
  sed -i '' "s/font_size = $RECORDING_FONT_SIZE/font_size = $DEFAULT_FONT_SIZE/g" "$WEZTERM_CONFIG"
fi
if [ ! -e "$TOGGLE" ]; then
  sed -i '' 's/config.default_prog/--config.default_prog/' "$WEZTERM_CONFIG"
else
  sed -i '' 's/--config.default_prog/config.default_prog/' "$WEZTERM_CONFIG"
fi

# Sketchybar
## Don't show clock while recording
SKETCHYBAR_CONFIG="$XDG_CONFIG_HOME/sketchybar/sketchybarrc"
if [ ! -e "$TOGGLE" ]; then
  sed -i '' 's|source "$ITEM_DIR/clock"|#source "$ITEM_DIR/clock"|g' "$SKETCHYBAR_CONFIG"
else
  sed -i '' 's|#source "$ITEM_DIR/clock"|source "$ITEM_DIR/clock"|g' "$SKETCHYBAR_CONFIG"
fi

# nvim
## Disable certain plugins while recording
NVIM_INIT_LUA="$XDG_CONFIG_HOME/nvim/init.lua"
if [ ! -e "$TOGGLE" ]; then
  sed -i '' "s/require('plugins.which-key')/--require('plugins.which-key')/g" "$NVIM_INIT_LUA"
else
  sed -i '' "s/--require('plugins.which-key')/require('plugins.which-key')/g" "$NVIM_INIT_LUA"
fi

# zsh
## Disable autosuggestions while recording
ZSH_CONFIG="$XDG_CONFIG_HOME/zsh/.zshrc"
if [ ! -e "$TOGGLE" ]; then
  sed -i '' '/zsh-users\/zsh-autosuggestions/d' "$ZSH_CONFIG"
else
  sed -i '' '/zsh-users\/zsh-syntax-highlighting/a\
  zsh-users/zsh-autosuggestions
' "$ZSH_CONFIG"
fi

# starship
if [ ! -e "$TOGGLE" ]; then
  stow -D -d ~/.dotfiles -t "$XDG_CONFIG_HOME" starship
  stow -d ~/playground/dotfiles/xdg_config_home -t "$XDG_CONFIG_HOME" starship-youtube
else
  stow -D -d ~/playground/dotfiles/xdg_config_home -t "$XDG_CONFIG_HOME" starship-youtube
  stow -d ~/.dotfiles -t "$XDG_CONFIG_HOME" starship
fi
