#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Load theme variables.
source "$CONFIG_DIR/theme"

# Configure general bar appearance.
bar=(
    position="$BAR_POSITION"
    height="$BAR_HEIGHT"
    y_offset="$BAR_Y_OFFSET"
    color="$BAR_COLOR"
    border_color="$BAR_BORDER_COLOR"
    padding_left="$BAR_PADDING"
    padding_right="$BAR_PADDING"
    corner_radius="$BAR_CORNER_RADIUS"
    margin="$BAR_MARGIN"
    blur_radius="$BAR_BLUR_RADIUS"
)
sketchybar --bar "${bar[@]}"

# Configure default values for later defined items.
default=(
  height="$BRACKET_HEIGHT"
  y_offset="$Y_OFFSET"
  background.color="$BACKGROUND_COLOR"
  background.border_color="$BACKGROUND_BORDER_COLOR"
  background.corner_radius="$BACKGROUND_CORNER_RADIUS"
  background.height="$BACKGROUND_HEIGHT"
  icon.drawing=off
  label.font="$LABEL_FONT"
  label.color="$LABEL_COLOR"
  label.highlight_color="$LABEL_HIGHLIGHT_COLOR"
  label.y_offset="$LABEL_Y_OFFSET"
  label.padding_left="$LABEL_PADDING"
  label.padding_right="$LABEL_PADDING"
)
sketchybar --default "${default[@]}"

# AeroSpace events
sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_meta_mode_enabled_changed

# AeroSpace workspace and meta mode indicators
sketchybar --add item workspaces_spacer_left left \
           --set      workspaces_spacer_left \
                      background.drawing=off \
                      padding_left=4

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item  workspace.$sid left \
               --subscribe workspace.$sid aerospace_workspace_change \
               --set       workspace.$sid \
                           label="$sid" \
                           label.highlight_color="$WORKSPACE_LABEL_HIGHLIGHT_COLOR" \
                           background.border_color="$WORKSPACE_BACKGROUND_BORDER_COLOR" \
                           click_script="aerospace workspace $sid" \
                           script="$PLUGIN_DIR/aerospace $sid"
done

sketchybar --add item  meta left \
           --subscribe meta aerospace_meta_mode_enabled_changed \
           --set       meta label.drawing=off \
                            label="m" \
                            background.border_color="$WORKSPACE_BACKGROUND_BORDER_COLOR" \
                            script="$PLUGIN_DIR/aerospace $AEROSPACE_META_MODE_ENABLED"

sketchybar --add item workspaces_spacer_right left \
           --set      workspaces_spacer_right \
                      background.drawing=off \
                      padding_right=4

sketchybar --add bracket workspaces workspaces_spacer_left meta /workspace\.*/ workspaces_spacer_right \
           --set         workspaces \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"

# Spacer between brackets
sketchybar --add item bracket_spacer left \
           --set      bracket_spacer \
                      background.drawing=off

# Front App
sketchybar --add item front_app_spacer_left left \
           --set      front_app_spacer_left \
                      background.drawing=off

sketchybar --add item  front_app left \
           --subscribe front_app front_app_switched \
           --set       front_app \
                       background.drawing=off \
                       label.color="$FRONT_APP_LABEL_COLOR" \
                       label.padding_left=0 \
                       label.padding_right=0 \
                       script="$PLUGIN_DIR/front_app"

sketchybar --add item front_app_spacer_right left \
           --set      front_app_spacer_right \
                      background.drawing=off

sketchybar --add bracket front_app_bracket front_app_spacer_left front_app front_app_spacer_right \
           --set         front_app_bracket \
                         background.color="$FRONT_APP_BACKGROUND_COLOR" \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"

# Clock
sketchybar --add item clock_spacer_right right \
           --set      clock_spacer_right \
                      background.drawing=off

sketchybar --add item clock right \
           --set      clock \
                      background.drawing=off \
                      label.padding_left=0 \
                      label.padding_right=0 \
                      update_freq=10 \
                      script="$PLUGIN_DIR/clock"

sketchybar --add item clock_spacer_left right \
           --set      clock_spacer_left \
                      background.drawing=off

sketchybar --add bracket clock_bracket clock_spacer_left clock clock_spacer_right \
           --set         clock_bracket \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"

# Automatically apply configuration changes
sketchybar --hotload on

# Force all scripts to run the first time (never do this in a script)
sketchybar --update

# Initialize focused workspace
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
