#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_meta_mode_enabled_changed

sketchybar --add item workspaces_spacer_left left \
           --set      workspaces_spacer_left \
                      label.drawing=off \
                      background.drawing=off \
                      width=7

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item  workspace.$sid left \
               --subscribe workspace.$sid aerospace_workspace_change \
               --set       workspace.$sid \
                           background.drawing=off \
                           click_script="aerospace workspace $sid" \
                           label="$sid" \
                           label.width="25" \
                           script="$PLUGIN_DIR/aerospace $sid"
done

sketchybar --add item  meta left \
           --subscribe meta aerospace_meta_mode_enabled_changed \
           --set       meta \
                            background.drawing=off \
                            label.drawing=off \
                            label.highlight=on \
                            label.font="$LABEL_HIGHLIGHT_FONT" \
                            label="[m]" \
                            label.padding_left=0 \
                            script="$PLUGIN_DIR/aerospace $AEROSPACE_META_MODE_ENABLED"

sketchybar --add item workspaces_spacer_right left \
           --set      workspaces_spacer_right \
                      label.drawing=off \
                      background.drawing=off \
                      width=7

sketchybar --add bracket workspaces workspaces_spacer_left /workspace\.*/ meta workspaces_spacer_right \
           --set         workspaces \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"
