#!/usr/bin/env bash

if [ "$SENDER" = "aerospace_meta_mode_enabled_changed" ]; then
  if [ "$AEROSPACE_META_MODE_ENABLED" = true ]; then
    sketchybar --set meta background.border_width=1 \
                          label.highlight=on
  else
    sketchybar --set meta background.border_width=0 \
                          label.highlight=off
  fi
fi

if [ "$SENDER" = "aerospace_workspace_change" ]; then
  if [ "$1" = "$FOCUSED_WORKSPACE" ]; then
    sketchybar --set $NAME background.border_width=1 \
                           label.highlight=on
  else
    sketchybar --set $NAME background.border_width=0 \
                           label.highlight=off
  fi
fi
