# tmux configuration file.
# ------------------------------------------------------------------------------
# Marco Peluso
# marcopeluso.com
# marco AT pelu DOT so
# ------------------------------------------------------------------------------


# Remove delay after an escape is input.
set-option -s escape-time 0

# Reload tmux.conf without killing the server.
bind-key r source-file ~/.tmux.conf \; \
           display-message "~/.tmux.conf sourced."

# Change the default command prefix to C-a (just like screen).
unbind-key C-b
set-option -g prefix C-a

# Press a in command mode to send the prefix to the shell.
bind-key a send-prefix

# Make the next-layout key repeatable.
bind-key -r space next-layout

# Make the next-window and previous-window keys repeatable.
bind-key -r n next-window
bind-key -r p previous-window

# Make the last-window and last-pane repeatable.
bind-key -r C-a last-pane
bind-key -r C-q last-window

# Clear the screen and the scrollback buffer.
bind-key C-l send-keys -R \; clear-history \; send-keys C-l

# Make the next pane key repeatable and add a previous pane key.
bind-key -r o select-pane -t :.+
bind-key -r O select-pane -t :.-

# Switch panes without taking the hands of the home row.
bind-key -r k select-pane -U
bind-key -r j select-pane -D
bind-key -r h select-pane -L
bind-key -r l select-pane -R

# Alternative window splitting keys.
# Also open new panes with the same pwd as the current pane.
# The way to do this changed since tmux version 1.9, so we do this using 'if-shell'
if-shell "[[ $(tmux -V | awk '{print ($2 >= 1.9)}') -eq 1 ]]" \
  'bind-key = split-window -h -c "#{pane_current_path}"' \
  'bind-key = split-window -h'
if-shell "[[ $(tmux -V | awk '{print ($2 >= 1.9)}') -eq 1 ]]" \
  'bind-key - split-window -v -c "#{pane_current_path}"' \
  'bind-key - split-window -v'

# Faster pane resizing.
bind-key -r up    resize-pane -U 10
bind-key -r down  resize-pane -D 10
bind-key -r left  resize-pane -L 10
bind-key -r right resize-pane -R 10

# Pane movement.
bind-key J command-prompt -p "Join pane from:" "join-pane -s '%%'"
bind-key S command-prompt -p "Send pane to:" "join-pane -t '%%'"

# Toggle statusbar.
bind-key b set-option status

# Activate mouse support across different versions using 'if-shell'.
if-shell "[[ $(tmux -V | awk '{print ($2 >= 2.1)}') -eq 1 ]]" \
  'set -g mouse on' \
  'set -g mode-mouse on; set -g mouse-resize-pane on; set -g mouse-select-pane on; set -g mouse-select-window on'

# Start windows indexing at '1'.
set-option -g base-index 1

# Enable UTF-8 support.
set-window-option -gq utf8 on

# Enable window activity notifications.
set-window-option -g monitor-activity on

# Rather than constraining window size to the maximum size of any client
# connected to the *session*, constrain window size to the maximum size of any
# client connected to *that window*. Much more reasonable.
set-window-option -g aggressive-resize on

# Configure status bar.
set-option -g status-right '[#(echo "$USER")@#H] - [#S:#I.#P] #W'

# Highlight active window.
set-window-option -g window-status-current-bg white
set-window-option -g window-status-current-fg red

# Attempt to set the window title, if the terminal appears to be an xterm.
set-option -g set-titles on
set-option -g set-titles-string '[#(echo "$USER")@#H] - [#S:#I.#P] #W' # [user@host] current window name [session name:current window index.current pane index

# Get 256 colors to work.
set -g default-terminal "screen-256color"

# Use vim keybindings in copy mode.
setw -g mode-keys vi

